include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - lib/services/model/**
    - lib/**/*.page.dart
  errors:
    todo: ignore
    undefined_prefixed_name: warning
    #该hint误报率过高
    unused_field: ignore
    use_build_context_synchronously: warning
    use_emit_synchronously: warning
  language:
    strict-casts: false # 严格类型转换，dynamic不再进行隐式类型转换
    strict-inference: false
    strict-raw-types: false
linter:
  rules:
    package_api_docs: true
    comment_references: true
    curly_braces_in_flow_control_structures: true
    library_names: true
    file_names: true
    library_prefixes: true
    camel_case_types: true
    camel_case_extensions: true
    non_constant_identifier_names: false
    constant_identifier_names: false
    use_rethrow_when_possible: true
    cancel_subscriptions: true
    close_sinks: true
    use_build_context_synchronously: true

custom_lint:
  debug: true
  verbose: true