blank_issues_enabled: true
contact_links:
  - name: Join the ByteDance Flutter Exchange Group. 加入字节跳动 Flutter 技术交流群
    url: https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=b07u55bb-68f0-4a4b-871d-687637766a68
    about: The topic of communication is not limited to UME, everything about Flutter can be spoken. 话题不局限于 UME，关于 Flutter 的一切均可畅所欲言。